import Head from "next/head";

export default function Home() {
  return (
    <Head>
      <title>Yume so | Stop buying unwated gifts</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

Home.defaultProps = {
  hideBar: true
};
